# Generated by Django 3.2.3 on 2026-05-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
