# Generated by Django 6.0.4 on 2026-06-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date_time'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor_branch_service', 'date_time'), name='unique_doctor_appointment_time'),
        ),
    ]
