DOCTORS = [
    {
        "email": "senya@ya.ru",
        "password": "Test1234",
        "first_name": "Арсений",
        "last_name": "Красоткин",
        "specialization": "Врач лабораторной диагностики",
        "work_started_at": "2019-06-20",
        "photo": "doctor_1_avatar.jpg",
        "branch_services": [13, 14, 15, 16, 17, 18],
    },
    {
        "email": "igor.zhaglo@ya.ru",
        "password": "Test1234",
        "first_name": "Игорь",
        "last_name": "Жагло",
        "specialization": "Терапевт",
        "work_started_at": "2018-09-01",
        "photo": "doctor_2_avatar.jpg",
        "branch_services": [1, 2, 25, 26, 27, 28, 29, 30],
    },
    {
        "email": "timofey.lyaskovskiy@ya.ru",
        "password": "Test1234",
        "first_name": "Тимофей",
        "last_name": "Лясковский",
        "specialization": "Кардиолог",
        "work_started_at": "2015-04-15",
        "photo": None,
        "branch_services": [3, 4, 9, 10],
    },
    {
        "email": "anastasia.morozova@ya.ru",
        "password": "Test1234",
        "first_name": "Анастасия",
        "last_name": "Морозова",
        "specialization": "Врач ультразвуковой диагностики",
        "work_started_at": "2020-02-10",
        "photo": None,
        "branch_services": [7, 8, 11, 12],
    },
    {
        "email": "petr.petrov@ya.ru",
        "password": "Test1234",
        "first_name": "Петр",
        "last_name": "Петров",
        "specialization": "Терапевт",
        "work_started_at": "2016-03-12",
        "photo": None,
        "branch_services": [1, 25, 27, 29],
    },
    {
        "email": "elena.volkova@ya.ru",
        "password": "Test1234",
        "first_name": "Елена",
        "last_name": "Волкова",
        "specialization": "Невролог",
        "work_started_at": "2017-10-05",
        "photo": None,
        "branch_services": [5, 6],
    },
    {
        "email": "sergey.orlov@ya.ru",
        "password": "Test1234",
        "first_name": "Сергей",
        "last_name": "Орлов",
        "specialization": "Врач ультразвуковой диагностики",
        "work_started_at": "2014-02-18",
        "photo": None,
        "branch_services": [7, 11],
    },
    {
        "email": "daria.kuznetsova@ya.ru",
        "password": "Test1234",
        "first_name": "Дарья",
        "last_name": "Кузнецова",
        "specialization": "Физиотерапевт",
        "work_started_at": "2021-04-09",
        "photo": None,
        "branch_services": [19, 20, 21, 22, 23, 24],
    },
    {
        "email": "nikolay.smirnov@ya.ru",
        "password": "Test1234",
        "first_name": "Николай",
        "last_name": "Смирнов",
        "specialization": "Врач восстановительной медицины",
        "work_started_at": "2013-11-21",
        "photo": None,
        "branch_services": [19, 21, 23],
    },
    {
        "email": "olga.fedorova@ya.ru",
        "password": "Test1234",
        "first_name": "Ольга",
        "last_name": "Федорова",
        "specialization": "Эндокринолог",
        "work_started_at": "2016-08-30",
        "photo": None,
        "branch_services": [13, 14, 17, 18],
    },
]